### ISSUE TITLE
Action reformats changelog file

### ISSUE THREAD

**Issue by vstrimaitis** [thomaseizinger/keep-a-changelog-new-release#7]
Running the action does not only move the `[Unreleased]` section to a new one, but also reformats the whole changelog file . For example, in my case lists were reformatted as so:

```
# Initially the list looked like this:
- abc
- def

# After running the action, it looks like this (i.e. more spaces are added):
-   abc
-   def
```

It would be great if this could be suppressed (or at least customized), since the reformatting could clash with other actions (e.g. linting).

**Comment by thomaseizinger** [comment]
Thanks for reporting!

The reformatting it is indeed an unfortunate side-effect. For the action to be reasonably robust, I chose to use a markdown parsing library so I could modify the AST directly instead of having to deal with markdown directly.

Unfortunately, that doesn't preserve whitespace like you outlined.

I don't have any plans on changing this at the moment. If it is important for your usecase to have a consistent formatting, I would suggest to run a markdown-formatter _after_ this action to bring it back into the formatting you desire.
